// Purpose: TS mirror of the shared tool registry — builds Anthropic tool specs,
// validates the config against the dispatcher, and runs each tool against Convex.
//
// The six tools have the SAME names/schemas as the Python CLI, but are implemented
// against Convex tables (the server has no access to the user's local files).

import type { AutomationConfig, ToolSpec } from "./config";
// `internal` is generated by `npx convex dev`. Until you run it, this import (and the
// _generated folder) will not exist — that is expected. See web/README.md.
import { internal } from "../convex/_generated/api";

/** The shape Anthropic's `messages.create({ tools })` expects. */
export interface AnthropicTool {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

/**
 * Minimal Convex action-context surface the dispatcher needs. The real
 * `ActionCtx` from convex/_generated/server is structurally compatible with this,
 * so you can pass it straight through.
 */
export interface ToolCtx {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runQuery: (reference: any, args?: any) => Promise<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runMutation: (reference: any, args?: any) => Promise<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runAction: (reference: any, args?: any) => Promise<any>;
}

/** Map the config's tool specs into the array Anthropic expects. */
export function buildAnthropicTools(config: AutomationConfig): AnthropicTool[] {
  return config.tools.map((spec: ToolSpec) => ({
    name: spec.name,
    description: spec.description,
    input_schema: spec.input_schema as unknown as Record<string, unknown>,
  }));
}

type ToolInput = Record<string, unknown>;
type Handler = (input: ToolInput, ctx: ToolCtx) => Promise<string>;

function str(input: ToolInput, key: string): string {
  const v = input[key];
  return typeof v === "string" ? v : "";
}

/**
 * The dispatcher registry, keyed by tool name (which equals `handler` in the config).
 * Every handler returns a plain string — exactly what gets put in the model's
 * `tool_result` block.
 */
const handlers: Record<string, Handler> = {
  // 1. Read the latest `documents` row whose name == path.
  read_document: async (input, ctx) => {
    const path = str(input, "path");
    if (!path) return "Error: `path` is required.";
    const doc = await ctx.runQuery(internal.store.getDocument, { name: path });
    if (!doc) return `No document named "${path}" was found in the workspace.`;
    return `--- ${doc.name} ---\n${doc.content}`;
  },

  // 2. List `documents` names, optionally filtered by substring.
  list_workspace: async (input, ctx) => {
    const pattern = str(input, "pattern");
    const names: string[] = await ctx.runQuery(internal.store.listDocuments, {
      pattern: pattern || undefined,
    });
    if (names.length === 0) {
      return pattern
        ? `No documents match "${pattern}".`
        : "The workspace has no documents yet.";
    }
    return `Documents (${names.length}):\n` + names.map((n) => `- ${n}`).join("\n");
  },

  // 3. Insert or replace a `documents` row.
  write_deliverable: async (input, ctx) => {
    const filename = str(input, "filename");
    const content = str(input, "content");
    if (!filename) return "Error: `filename` is required.";
    await ctx.runMutation(internal.store.writeDocument, { name: filename, content });
    return `Wrote deliverable "${filename}" (${content.length} characters).`;
  },

  // 4. Append a structured record to the `records` table.
  save_record: async (input, ctx) => {
    const table = str(input, "table");
    const data = (input["data"] ?? {}) as Record<string, unknown>;
    if (!table) return "Error: `table` is required.";
    await ctx.runMutation(internal.store.addRecord, { table, data });
    return `Saved 1 record to "${table}": ${JSON.stringify(data)}`;
  },

  // 5. Substring-search records in a table.
  lookup_record: async (input, ctx) => {
    const table = str(input, "table");
    const query = str(input, "query");
    if (!table) return "Error: `table` is required.";
    const rows: Array<{ data: Record<string, unknown> }> = await ctx.runQuery(
      internal.store.queryRecords,
      { table, query: query || undefined },
    );
    if (rows.length === 0) {
      return query
        ? `No records in "${table}" match "${query}".`
        : `No records in "${table}" yet.`;
    }
    const body = rows.map((r, i) => `${i + 1}. ${JSON.stringify(r.data)}`).join("\n");
    return `Found ${rows.length} record(s) in "${table}":\n${body}`;
  },

  // 6. Create a follow-up task.
  create_task: async (input, ctx) => {
    const title = str(input, "title");
    const due = str(input, "due");
    const notes = str(input, "notes");
    if (!title) return "Error: `title` is required.";
    await ctx.runMutation(internal.store.addTask, {
      title,
      due: due || undefined,
      notes: notes || undefined,
    });
    return `Created task "${title}"${due ? ` (due ${due})` : ""}.`;
  },
};

// >>> SCAFFOLD:DOMAIN_TOOLS <<<
Object.assign(handlers, {
  // Score and tier a lead (pure logic, no Convex needed).
  qualify_lead: async (input) => {
    const name = (input["name"] as string) || "(unnamed)";
    const intent = (input["intent"] as string) || "buy";
    let score = 0;
    const reasons: string[] = [];
    const budget = input["budget"];
    if (typeof budget === "number" && budget > 0) {
      score += 30;
      reasons.push("budget provided");
    }
    const tw = input["timeline_weeks"];
    if (typeof tw === "number") {
      if (tw <= 4) {
        score += 40;
        reasons.push("urgent timeline (<=4w)");
      } else if (tw <= 12) {
        score += 25;
        reasons.push("near-term timeline (<=12w)");
      } else {
        score += 10;
        reasons.push("longer timeline");
      }
    }
    if (input["financing_ready"]) {
      score += 30;
      reasons.push("financing ready");
    }
    const tier = score >= 70 ? "hot" : score >= 40 ? "warm" : "cold";
    return `Lead "${name}" (${intent}): tier=${tier} score=${score}/100. Factors: ${
      reasons.join(", ") || "minimal info"
    }.`;
  },

  // Price guidance from comps (pure logic).
  comparable_analysis: async (input) => {
    const subject = (input["subject_address"] as string) || "(subject)";
    const comps = (input["comps"] as Array<Record<string, unknown>>) || [];
    const prices = comps
      .map((c) => c?.["price"])
      .filter((p): p is number => typeof p === "number")
      .sort((a, b) => a - b);
    if (prices.length === 0)
      return `No usable comp prices for ${subject}; provide comps with numeric "price".`;
    const n = prices.length;
    const median = n % 2 ? prices[(n - 1) / 2] : (prices[n / 2 - 1] + prices[n / 2]) / 2;
    const low = Math.round(median * 0.95);
    const high = Math.round(median * 1.05);
    const fmt = (x: number) => Math.round(x).toLocaleString();
    return `Comparable analysis for ${subject} (${n} comps): min ${fmt(prices[0])}, median ${fmt(
      median,
    )}, max ${fmt(prices[n - 1])}. Suggested list range: ${fmt(low)}-${fmt(
      high,
    )}. Sanity-check inputs before quoting.`;
  },

  // Draft a listing sheet into the documents table (draft only).
  generate_listing_sheet: async (input, ctx) => {
    const address = (input["address"] as string) || "(address)";
    const price = input["price"];
    const beds = input["beds"];
    const baths = input["baths"];
    const sqft = input["sqft"];
    const features = (input["features"] as string[]) || [];
    const lines: string[] = [`# ${address}`, ""];
    if (typeof price === "number") lines.push(`**Price:** ${price.toLocaleString()}`);
    const specs: string[] = [];
    if (beds != null) specs.push(`${beds} bd`);
    if (baths != null) specs.push(`${baths} ba`);
    if (sqft != null) specs.push(`${sqft} sqft`);
    if (specs.length) lines.push(`**Specs:** ${specs.join(" | ")}`);
    if (features.length) lines.push("", "## Highlights", ...features.map((f) => `- ${f}`));
    lines.push("", "_Draft - review before publishing to any portal._", "");
    const body = lines.join("\n");
    const filename = address.toLowerCase().replace(/[, ]+/g, "-") + "-listing.md";
    await ctx.runMutation(internal.store.writeDocument, { name: filename, content: body });
    return `Listing sheet drafted to "${filename}" (${body.length} chars). Review before publishing.`;
  },

  // Record a viewing in the records table.
  schedule_viewing: async (input, ctx) => {
    const client = input["client"] as string;
    const address = input["address"] as string;
    const dt = input["datetime"] as string;
    if (!client || !address || !dt)
      return "Error: `client`, `address`, and `datetime` are all required.";
    await ctx.runMutation(internal.store.addRecord, {
      table: "viewings",
      data: { client, address, datetime: dt, status: "pending_confirmation" },
    });
    return `Recorded viewing: ${client} @ ${address} on ${dt} (pending confirmation). Add the calendar event after the client confirms.`;
  },
});

/** Names the dispatcher knows how to run. */
export const KNOWN_HANDLERS: readonly string[] = Object.keys(handlers);

/**
 * Assert every `config.tools[*].handler` is implemented here. Throws (listing the
 * gaps) so a misconfigured contract fails loudly at startup instead of mid-run.
 */
export function validateConfigTools(config: AutomationConfig): void {
  const missing = config.tools
    .map((t) => t.handler)
    .filter((h) => !(h in handlers));
  if (missing.length > 0) {
    throw new Error(
      `automation.config.json references unknown tool handler(s): ${missing.join(
        ", ",
      )}. Known handlers: ${KNOWN_HANDLERS.join(", ")}.`,
    );
  }
}

/**
 * Execute a single tool call and return the string the model should see as its
 * `tool_result`. `name` is the Anthropic tool name (identical to the config handler).
 */
export async function dispatchTool(
  name: string,
  input: ToolInput,
  ctx: ToolCtx,
): Promise<string> {
  const handler = handlers[name];
  if (!handler) {
    return `Error: no handler registered for tool "${name}".`;
  }
  try {
    return await handler(input, ctx);
  } catch (err) {
    return `Error while running "${name}": ${
      err instanceof Error ? err.message : String(err)
    }`;
  }
}
